export const icons = {
  arrowDown: require('../assets/icon/arrowd.svg'),
  arrowRight: require('../assets/icon/arrowr.svg'),
  arrowLeft: require('../assets/icon/arrowl.svg'),
  fire: require('../assets/icon/fire.svg'),
  flower: require('../assets/icon/flower.png'),
  fruit: require('../assets/icon/fruit.png'),
  home: require('../assets/icon/home.svg'),
  lesson: require('../assets/icon/lesson.svg'),
  psychiatry: require('../assets/icon/psychiatry.png'),
  star: require('../assets/icon/star.svg'),
  water: require('../assets/icon/water.png'),
  sunny: require('../assets/icon/sunny.png'),
  rank: require('../assets/icon/rank.svg'),
  announce: require('../assets/icon/announce.svg'),
};
export const images = {
  capy: require('../assets/image/Capy.png'),
  vietnamFlag: require('../assets/image/vietnam_flag.png'),
  japaneseFlag: require('../assets/image/japanese_flag.png'),
  google: require('../assets/image/google.png'),
  local_fire: require('../assets/image/local_fire.png'),
  circle_notifications: require('../assets/image/circle_notifications.png'),
  home1: require('../assets/image/home1.png'),
  account_circle: require('../assets/image/account_circle.png'),
};
